/*
Description
Grove IIC ADC
VCC : +5.0V
SIG : 0/+6.0V

(Sig) +6.0V ->10k/10k -> +3.0V (Vin)

ADC121C021
Va :+3.0
Vin 0V/+3.0V
AD 12bit : 3.0/4096=0.73mV
Sig 10k/10k Vin 6.0/4096=1.46mV

ACS714 : +5A -5A current to voltage converter
VCC +5.0
Vout=Iin/185 + Vcc/2(2.5)
Iin = 0A -> 2.5V

Iin 50mA (5V 100ohm)
Vout  50/185 + Vcc/2(2.5)=2.5093V

2015/05/14
result : 2.50(min) 2.57(,ax)

2015/05/14 HK copy

original: http://www.seeedstudio.com/wiki/Grove_-_I2C_ADC
*/

#include <Wire.h>
#include <Streaming.h>

#define ADDR_ADC121             0x55  // IIC Slave Address

/*
This reference voltage V_ref is more accurate than one generated by microcontroller.
And you can make that more accurate by measuring the voltage between VA and GND
and use that value to replace 3.00
*/
#define V_REF 3.00    // ADC121C021 Va

#define REG_ADDR_RESULT         0x00
#define REG_ADDR_ALERT          0x01
#define REG_ADDR_CONFIG         0x02
#define REG_ADDR_LIMITL         0x03
#define REG_ADDR_LIMITH         0x04
#define REG_ADDR_HYST           0x05
#define REG_ADDR_CONVL          0x06
#define REG_ADDR_CONVH          0x07

int getData;

void init_adc()
{
  Wire.beginTransmission(ADDR_ADC121);        // transmit to device
  Wire.write(REG_ADDR_CONFIG);                // Configuration Register
  // Tconvert x 32 : 27ksps
  // Tconver : 
  Wire.write(0x20);
  Wire.endTransmission();            // IIC go
}

void read_adc()     //unsigned int *data
{


  Wire.beginTransmission(ADDR_ADC121);        // transmit to device
  Wire.write(REG_ADDR_RESULT);                // get result
  Wire.endTransmission();                      // IIC go

  Wire.requestFrom(ADDR_ADC121, 2);           // request 2byte from device
  delay(1);
  if (Wire.available() <= 2)
  {
    getData = (Wire.read() & 0x0f) << 8;
    getData |= Wire.read();

//    Uncomment blow to check raw data
//    Serial.println(getData, DEC);
  }
  
  Serial.write("H");                        // header
  Serial.write(highByte(getData));          // high byte
  Serial.write(lowByte(getData));           // low byte
  delay(5);
}
void setup()
{
  Serial.begin(9600);    //9600 baud rate
  Wire.begin();
  init_adc();
}

void loop()
{ 
  read_adc();                               // adcRead
  // wait time 50ms
  delay(50);
}
