# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serial_plot.ui'
#
# Created: Tue Jul 14 10:17:25 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.vl_raw = QtGui.QVBoxLayout()
        self.vl_raw.setObjectName("vl_raw")
        self.verticalLayout_5.addLayout(self.vl_raw)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.vl_fft = QtGui.QVBoxLayout()
        self.vl_fft.setObjectName("vl_fft")
        self.verticalLayout_6.addLayout(self.vl_fft)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.trig_radio_button = QtGui.QRadioButton(self.groupBox)
        self.trig_radio_button.setObjectName("trig_radio_button")
        self.gridLayout.addWidget(self.trig_radio_button, 0, 0, 1, 1)
        self.run_radio_button = QtGui.QRadioButton(self.groupBox)
        self.run_radio_button.setObjectName("run_radio_button")
        self.gridLayout.addWidget(self.run_radio_button, 1, 0, 1, 1)
        self.run_push_button = QtGui.QPushButton(self.groupBox)
        self.run_push_button.setObjectName("run_push_button")
        self.gridLayout.addWidget(self.run_push_button, 2, 0, 1, 1)
        self.saveraw_push_button = QtGui.QPushButton(self.groupBox)
        self.saveraw_push_button.setObjectName("saveraw_push_button")
        self.gridLayout.addWidget(self.saveraw_push_button, 2, 1, 1, 1)
        self.stop_push_button = QtGui.QPushButton(self.groupBox)
        self.stop_push_button.setObjectName("stop_push_button")
        self.gridLayout.addWidget(self.stop_push_button, 3, 0, 1, 1)
        self.savefft_push_button = QtGui.QPushButton(self.groupBox)
        self.savefft_push_button.setObjectName("savefft_push_button")
        self.gridLayout.addWidget(self.savefft_push_button, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "RAW", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "FFT", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Control Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.trig_radio_button.setText(QtGui.QApplication.translate("MainWindow", "Triger", None, QtGui.QApplication.UnicodeUTF8))
        self.run_radio_button.setText(QtGui.QApplication.translate("MainWindow", "Free Run", None, QtGui.QApplication.UnicodeUTF8))
        self.run_push_button.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.saveraw_push_button.setText(QtGui.QApplication.translate("MainWindow", "Save RAW", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_push_button.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.savefft_push_button.setText(QtGui.QApplication.translate("MainWindow", "Save FFT", None, QtGui.QApplication.UnicodeUTF8))

