#include <Wire.h>
#include <Streaming.h>

#define ADDR_ADC121             0x55

/*
This reference voltage V_ref is more accurate than one generated by microcontroller.
And you can make that more accurate by measuring the voltage between VA and GND
and use that value to replace 3.00
*/
#define V_REF 3.00

#define REG_ADDR_RESULT         0x00
#define REG_ADDR_ALERT          0x01
#define REG_ADDR_CONFIG         0x02
#define REG_ADDR_LIMITL         0x03
#define REG_ADDR_LIMITH         0x04
#define REG_ADDR_HYST           0x05
#define REG_ADDR_CONVL          0x06
#define REG_ADDR_CONVH          0x07

int getData;

void init_adc()
{
  Wire.beginTransmission(ADDR_ADC121);        // transmit to device
  Wire.write(REG_ADDR_CONFIG);                // Configuration Register
  Wire.write(0x8);
  Wire.endTransmission();
}

void read_adc()     //unsigned int *data
{


  Wire.beginTransmission(ADDR_ADC121);        // transmit to device
  Wire.write(REG_ADDR_RESULT);                // get result
  Wire.endTransmission();

  Wire.requestFrom(ADDR_ADC121, 2);           // request 2byte from device
  delay(1);
  if (Wire.available() <= 2)
  {
    getData = (Wire.read() & 0x0f) << 8;
    getData |= Wire.read();

//    Uncomment blow to check raw data
    Serial.println(getData, DEC);
  }
  
//  Serial.write("H");                        // header
//  Serial.write(highByte(getData));          // high byte
//  Serial.write(lowByte(getData));           // low byte
  delay(5);
}
void setup()
{
  Serial.begin(9600);
  Wire.begin();
  init_adc();
}

void loop()
{ read_adc();                               // adcRead
  delay(50);
}
